name: dart-101
description: A Package containing all the Code for learning dart
version: 1.0.0
repository: https://github.com/arunabh-a/Dart-Learn

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
